[project]
name = "e-commerce-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.5.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
